GuanLiPingTai/urls.py
from django.contrib import admin
from django.urls import path
from web.views import zero, account, check, my_celery

urlpatterns = [
    path("zero/", zero.zero),
    path("account/login/", account.login),
    path("account/register/", account.admin_add),
    path('image/code/', account.image_code),
    path('new/', account.new),

    # 账单管理
    path('check/list/', check.check_list),
    path('check/add/', check.check_model_form_add),
    path('check/<int:nid>/edit/', check.check_edit),
    path('check/<int:nid>/delete/', check.check_delete),
    path('check/deplay/', check.check_deplay),

    # celery并发异步
    path('celery/test/', my_celery.test),


]

web/forms/account.py
from django import forms
from web.utils.encrypt import md5


class BootStrap:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 循环ModelForm中的所有字段，给每个字段的插件设置
        for name, field in self.fields.items():
            # 字段中有属性，保留原来的属性，没有属性，才增加。
            if field.widget.attrs:
                field.widget.attrs["class"] = "form-control"
                field.widget.attrs["placeholder"] = field.label
            else:
                field.widget.attrs = {
                    "class": "form-control",
                    "placeholder": field.label
                }


class BootStrapModelForm(BootStrap, forms.ModelForm):
    pass


class BootStrapForm(BootStrap, forms.Form):
    pass

class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )

    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

web/views/zero.py
"""
初始界面
需求：有登录与注册按钮，点击之后跳转至对应的界面
     背景图
"""
from django.shortcuts import render, HttpResponse, redirect

def zero(request):
    return render(request, 'zero.html')

web/templates/ceshi.html
<table class="table table-bordered">
  ...
</table>

web/templates/check_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建账单 </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label>时间</label>
                        <input id="dt"  type="text" autocomplete="off" class="form-control" placeholder="时间" name="time"/>
                    </div>

                    <div class="form-group">
                        <label>金钱</label>
                        <input type="text" class="form-control" placeholder="金钱" name="money"/>
                    </div>

                    <div class="form-group">
                        <label>用途</label>
                        <input type="text" class="form-control" placeholder="用途" name="uses"/>
                    </div>


                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}



{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#dt').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });

        })
    </script>
{% endblock %}

web/templates/check_deplay.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        body {
            margin: 0;
        }

        img {
            width: 100%;
            height: 100%;
        }


        .container {
            width: 1226px;
            margin: 0 auto;
        }


        .header {
            background: #333;
        }


        .header .menu {
            float: left;
            color: white;
        }


        .header a {
            color: #b0b0b0;
            line-height: 60px;
            display: inline-block;
            font-size: 15px;
            margin-right: 10px;

            text-decoration: none;
        }

        .header a:hover {
            color: white;
        }



        .sub-header .logo a {
            margin-top: 22px;
            display: inline-block
        }

        .sub-header .logo a img {
            height: 56px;
            width: 56px;
        }



        .sub-header .menu-list a {
            display: inline-block;
            padding: 0 10px;
            color: #333;
            font-size: 16px;
            text-decoration: none;
        }

        .sub-header .menu-list a:hover {
            color: #ff6700;
        }


        .news .channel .item a{
            display: inline-block;
            font-size: 12px;
            padding-top: 18px;
            color: #fff;
            text-decoration: none;

            opacity: 0.7;
        }
        .news .channel .item a:hover{
            opacity: 1;
        }
        .news .channel .item  img{
            height: 24px;
            width: 24px;
            display: block;
            margin: 0 auto 4px;

        }


    </style>
</head>
<body>

<div class="header">
    <div class="container">
        <div class="menu">
            <a href="/check/list/">账单管理</a>
            <a href="https://www.mi.com/">待办事项管理</a>
            <a href="https://www.mi.com/">日志管理</a>

        </div>
        <div style="clear: both"></div>
    </div>
</div>

<div style="height: 20px">

</div>

<table class="table table-bordered" >
  <thead>
    <tr>
      <th>时间</th>
      <th>金钱</th>
    </tr>
  </thead>
  <tbody>
    {% for time, money in result_dict.items %}
    <tr>
      <td>{{ time }}</td>
      <td>{{ money }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


</body>
</html>

web/templates/check_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 编辑账单 </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/check_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        body {
            margin: 0;
        }

        img {
            width: 100%;
            height: 100%;
        }


        .container {
            width: 1226px;
            margin: 0 auto;
        }


        .header {
            background: #333;
        }


        .header .menu {
            float: left;
            color: white;
        }


        .header a {
            color: #b0b0b0;
            line-height: 60px;
            display: inline-block;
            font-size: 15px;
            margin-right: 10px;

            text-decoration: none;
        }

        .header a:hover {
            color: white;
        }



        .sub-header .logo a {
            margin-top: 22px;
            display: inline-block
        }

        .sub-header .logo a img {
            height: 56px;
            width: 56px;
        }



        .sub-header .menu-list a {
            display: inline-block;
            padding: 0 10px;
            color: #333;
            font-size: 16px;
            text-decoration: none;
        }

        .sub-header .menu-list a:hover {
            color: #ff6700;
        }


        .news .channel .item a{
            display: inline-block;
            font-size: 12px;
            padding-top: 18px;
            color: #fff;
            text-decoration: none;

            opacity: 0.7;
        }
        .news .channel .item a:hover{
            opacity: 1;
        }
        .news .channel .item  img{
            height: 24px;
            width: 24px;
            display: block;
            margin: 0 auto 4px;

        }


    </style>
</head>
<body>

<div class="header">
    <div class="container">
        <div class="menu">
            <a href="/check/list/">账单管理</a>
            <a href="https://www.mi.com/">待办事项管理</a>
            <a href="https://www.mi.com/">日志管理</a>

        </div>
        <div style="clear: both"></div>
    </div>
</div>

<div style="height: 20px">

</div>

<div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/check/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建账单
            </a>
            <a class="btn btn-success" href="/check/deplay/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                每日汇总
            </a>
        </div>






 <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>日期</th>
                    <th>费用</th>
                    <th>用途</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.time|date:"Y-m-d" }}</th>
                        <td>{{ obj.money }}</td>
                        <td>{{ obj.uses }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/check/{{obj.id}}/edit">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/check/{{obj.id}}/delete">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
 </div>





</body>
</html>

web/templates/denglu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

web/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> 日志管理系统 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">账单管理</a></li>
                <li><a href="/user/list/">待办事项管理</a></li>
                <li><a href="/pretty/list/">日志管理</a></li>



            </ul>
        </div>
    </div>
</nav>

<div>
    {% block content %}{% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

web/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

web/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            margin: 0;
        }

        img {
            width: 100%;
            height: 100%;
        }

        .left {
            float: left;
        }

        .container {
            width: 1226px;
            margin: 0 auto;
        }


        .header {
            background: #333;
        }


        .header .menu {
            float: left;
            color: white;
        }


        .header a {
            color: #b0b0b0;
            line-height: 60px;
            display: inline-block;
            font-size: 15px;
            margin-right: 10px;

            text-decoration: none;
        }

        .header a:hover {
            color: white;
        }



        .sub-header .logo a {
            margin-top: 22px;
            display: inline-block
        }

        .sub-header .logo a img {
            height: 56px;
            width: 56px;
        }



        .sub-header .menu-list a {
            display: inline-block;
            padding: 0 10px;
            color: #333;
            font-size: 16px;
            text-decoration: none;
        }

        .sub-header .menu-list a:hover {
            color: #ff6700;
        }



        .slider .sd-img {
            width: 1226px;
            height: 600px;
        }

        .news{
            margin-top: 14px;
        }


        .news .channel .item a{
            display: inline-block;
            font-size: 12px;
            padding-top: 18px;
            color: #fff;
            text-decoration: none;

            opacity: 0.7;
        }
        .news .channel .item a:hover{
            opacity: 1;
        }
        .news .channel .item  img{
            height: 24px;
            width: 24px;
            display: block;
            margin: 0 auto 4px;

        }

        .news .list-item {
            width: 280px;
            height: 170px;
        }

    </style>
</head>
<body>

<div class="header">
    <div class="container">
        <div class="menu">
            <a href="/check/list/">账单管理</a>
            <a href="https://www.mi.com/">待办事项管理</a>
            <a href="https://www.mi.com/">日志管理</a>
            <a href="/celery/test/">celery实现并发异步</a>

        </div>
        <div style="clear: both"></div>
    </div>
</div>

<div style="height: 20px">

</div>



<div class="slider">
    <div class="container">
        <div class="sd-img">
            <img src="../static/img/03.jpg" alt="">
        </div>
    </div>
</div>


<div class="news">
    <div class="container">

        <div class="list-item left" style="margin-left: 20px">
            <img src="../static/img/04.jpg"/>
        </div>
        <div class="list-item left" style="margin-left: 20px">
            <img src="../static/img/05.jpg"/>
        </div>
        <div class="list-item left" style="margin-left: 20px">
            <img src="../static/img/06.jpg"/>
        </div>
        <div class="list-item left" style="margin-left: 20px">
            <img src="../static/img/02.jpg"/>
        </div>

        <div class="clear:both"></div>
    </div>
</div>


</body>
</html>

web/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
                /* 背景图片样式规则 */
        body {
            background-image: url("{% static 'img/02.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }

        .custom-input {
            background-color: transparent; /* 使输入框背景透明 */
            color: white; /* 输入框文本颜色 */
        /* 其他样式属性 */
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户注册</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>重复密码</label>
            {{ form.confirm_password }}
            <span style="color: red;">{{ form.confirm_password.errors.0 }}</span>
        </div>
        <input type="submit" value="注册" class="btn btn-primary">
    </form>
</div>

</body>
</html>

web/templates/zero.html
<!DOCTYPE html>
<html>
<head>
    <title>Login and Register</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background: url("../static/img/02.jpg") no-repeat center center fixed;
            background-size: cover;
        }

        .container {
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .container button {
            padding: 10px 20px;
            margin: 10px;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="/account/login/"><button>登录</button></a>
        <a href="/account/register/"><button>注册</button></a>
    </div>
</body>
</html>